version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: db
      # POSTGRES_INITDB_ARGS: "--timezone='Asia/Tokyo'"

  backend:
    build: .
    container_name: backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend_network
    ports:
      - 8000:8000

networks:
  backend_network:

volumes:
  db_data: